### PR TITLE
Allow module to fail gracefully in prerender mode.

### PR DESCRIPTION
**Pull request by doctyper**
Hi. This module works well in development mode but throws an error attempting to use it on the server (window is undefined). This is a workaround for that use-case. If window is undefined the module simply passes the styles along.

Also not sure how you're compiling into `dist`, perhaps you can add a script for that in `package.json`?

### CODE REVIEW

**Comment by cgarvis** [comment]
Can you amend your PR without rebuilding this dist file.

**Comment by doctyper** [comment]
Done.

**Comment by cgarvis** [comment]
Can you squash these commits into 1 so we have a "cleaner" history?

**Comment by doctyper** [comment]
Thanks. Can you bump the version please?

**Pull request merged**
